# Site settings
title: Deep Garbage
email: deepgarbage@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rooting through your data garbage.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deepgarbage.info" # the base hostname & protocol for your site
twitter_username: deepgarbage
github_username:  jekyll

# Build settings
markdown: kramdown
